### ISSUE TITLE
Alert triggered but no email sent

### ISSUE THREAD

**Issue by akan70** [dingtools/Ding-Issue-Tracker#15]
2021 8 2 22:45:45 gmt+8

"I just did a test, and seems like I’m not getting email alerts anymore. I checked and alert is shown as triggered on website, but never received email. I’ve checked my Junk and spam folders and nothing there. Any ideas?" 

![IMG_20210802_162707_754](https://user-images.githubusercontent.com/85875285/127885905-94d7256b-03ab-4553-b9fd-5046c20a6c0f.jpg)

**Comment by martincoster** [comment]
Issue was due to spam filter blocking alert emails. Suggest this issue is closed.
