### ISSUE TITLE
Feature Request: Manually Delete Tokens

### ISSUE THREAD

**Issue by trizzant** [dingtools/Ding-Issue-Tracker#2]
Ability to delete tokens manually on the My Wallet list. This would help remove the honeypots that show a incorrect amount of Total. Would also need a undo feature in case you remove one by accident or want to reenable for any reason.

![image](https://user-images.githubusercontent.com/6733513/127216844-543115f3-5b54-4377-8c92-112fdad3c596.png)

**Comment by Internet-Sysop** [comment]
Agreed this is an important one

**Comment by trizzant** [comment]
Any update on this one? I really can't use the portfolio part until this is completed. I have over a hundred I need to remove.
