### ISSUE TITLE
Took 8 minutes to get a text after price hit

### ISSUE THREAD

**Issue by dingtools** [dingtools/Ding-Issue-Tracker#5]
Token details

https://poocoin.app/tokens/0xeb8945d9eb7c48d4a1dd7d12eb86820f98f166e3

**Comment by trizzant** [comment]
same here: https://poocoin.app/tokens/0x1633b7157e7638c4d6593436111bf125ee74703f

**Comment by trizzant** [comment]
Here is another example. The following token's alert arrived 9 minutes after the price break. 
https://poocoin.app/tokens/0x12c5cf182c25606f02ee6d59af57ac8e55d3791f

alert set at: $0.00025
price break $0.0002518 @ 2:37:23 PM
sms alert @ 2:46 PM

**Comment by trizzant** [comment]
Is it supposed to trigger when it crosses the price or when it closes above the price? Also, is the live price the same as I would see in poocoin?
