### ISSUE TITLE
Disable ability to search by name

### ISSUE THREAD

**Issue by trizzant** [dingtools/Ding-Issue-Tracker#8]
One of the worst things you can do on poocoin is search by name. You will inevitably end up loosing money in a scam token with the same name. This is especially true for hyped up token launches. Forcing a contract only in the search would save people so much disappointment. Just a thought.

**Comment by dingtools** [comment]
This is more of a user/community education issue. There is a balance that must be struck between user experience and security. It more convenient for the user to search by name and takes less steps than first finding the contract address and pasting it in. For most Ding use cases it is not a huge issue to get the contract wrong ATM unless you hook it up to a trading bot. If that's the case then the user must do their due diligence. Adding more steps like finding out the contract address would be a less user experience then most people are used to

**Comment by trizzant** [comment]
That makes sense. Thank you for your response.
